name: dance-env
channels:
  - defaults
  - conda-forge
dependencies:
  # Core conda packages
  - python=3.10
  - pip
  - numpy
  - opencv
  - matplotlib
  - jupyter
  - ipykernel
  - psutil
  - setuptools
  - wheel
  - sqlite
  - tk
  - xz
  - zlib

  # pip dependencies
  - pip:
      - absl-py==2.3.1
      - altair==5.5.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.2.10
      - fonttools==4.60.0
      - gast==0.4.0
      - gitdb==4.0.12
      - GitPython==3.1.45
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.75.0
      - h5py==3.14.0
      - idna==3.10
      - jax==0.4.30
      - jaxlib==0.4.30
      - Jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==2.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - Markdown==3.9
      - MarkupSafe==3.0.2
      - matplotlib==3.10.6
      - mediapipe==0.10.21
      - ml_dtypes==0.5.3
      - narwhals==2.5.0
      - numpy==1.23.5
      - oauthlib==3.3.1
      - opencv-contrib-python==4.11.0.86
      - opt_einsum==3.4.0
      - pandas==2.3.2
      - pillow==11.3.0
      - protobuf==4.25.8
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1_modules==0.4.2
      - pycparser==2.23
      - pydeck==0.9.1
      - pygame==2.6.1
      - pyparsing==3.2.5
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - smmap==5.0.2
      - sounddevice==0.5.2
      - streamlit==1.50.0
      - tenacity==9.1.2
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.2
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - watchdog==6.0.0
      - Werkzeug==3.1.3
      - wrapt==1.14.2
